{% set name = "soapysdr-module-uhd" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/pothosware/SoapyUHD/archive/soapy-uhd-{{ version }}.tar.gz
  sha256: 9779cce2e732cd41905b6cf8ea85edbbf51b1ac918e6180bd4891eebb4c8d085
  patches:
    - 0001-SoapyUHDDevice-implemented-getNativeDeviceHandle.patch
    - 0002-UHDSoapyDevice-Add-cctype-header-needed-for-std-isdi.patch
    - 0003-Fix-for-getBandwidthRange-for-SOAPY_SDR_RX.patch
    - 0004-Fix-get_tree-for-X300-on-UHD-4.0.patch
    - 0008-Added-missing-streaming-and-frequency-arg-info.patch
    - 0009-Set-C-14-which-is-required-in-UHD-headers.patch
    - 0010-Define-post_input_action-post_output_action-for-UHD-.patch

build:
  number: 15
  run_exports:
    - {{ pin_subpackage('soapysdr-module-uhd', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - libboost-headers
    - soapysdr
    - uhd

outputs:
  - name: soapysdr-module-uhd
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
      host:
        - libboost-headers
        - soapysdr
        - uhd
    files:
      - lib/SoapySDR/modules*/libuhdSupport.so  # [not win]
      - Library/lib/SoapySDR/modules*/uhdSupport.dll  # [win]
    test:
      commands:
        - test -f $PREFIX/lib/SoapySDR/modules{{ soapysdr }}/libuhdSupport.so  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\SoapySDR\\modules{{ soapysdr }}\\uhdSupport.dll exit 1  # [win]

        - SoapySDRUtil --info
        - SoapySDRUtil --info | grep uhdSupport  # [not win]
        - SoapySDRUtil --info | findstr /l uhdSupport  # [win]

  - name: uhd-soapysdr
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
      host:
        - libboost-headers
        - soapysdr
        - uhd
    files:
      - lib/uhd/modules/libsoapySupport.so  # [not win]
      - Library/lib/uhd/modules/soapySupport.dll  # [win]
    test:
      commands:
        - test -f $PREFIX/lib/uhd/modules/libsoapySupport.so  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\uhd\\modules\\soapySupport.dll exit 1  # [win]

about:
  home: https://github.com/pothosware/SoapyUHD/wiki
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Soapy SDR plugin for UHD supported SDR devices
  description: |
    The Soapy UHD project provides a plugin module to use UHD devices within the
    SoapySDR API and software that supports SoapySDR. In addition, the project
    provides a UHD module to use any SoapySDR device within the UHD API and UHD
    supported software.
  doc_url: https://github.com/pothosware/SoapyUHD/wiki
  dev_url: https://github.com/pothosware/SoapyUHD

extra:
  feedstock-name: soapysdr-module-uhd
  recipe-maintainers:
    - ryanvolz
